from pathlib import Path
from typing import List
from models.language_spec import LanguageSpecification


class ExampleGenerator:
    """Generates example programs in the language"""

    def __init__(self, spec: LanguageSpecification):
        self.spec = spec

    def generate_all(self, output_dir: Path) -> List[str]:
        """Generate all example files"""
        generated_files = []

        examples_dir = output_dir / "examples"
        examples_dir.mkdir(exist_ok=True)

        # Generate Hello World
        hello_world_file = examples_dir / f"hello_world{self.spec.file_extension}"
        with open(hello_world_file, 'w') as f:
            f.write(self.generate_hello_world())
        generated_files.append(str(hello_world_file))

        # Generate Fibonacci
        fibonacci_file = examples_dir / f"fibonacci{self.spec.file_extension}"
        with open(fibonacci_file, 'w') as f:
            f.write(self.generate_fibonacci())
        generated_files.append(str(fibonacci_file))

        # Generate additional examples
        examples_readme = examples_dir / "README.md"
        with open(examples_readme, 'w') as f:
            f.write(self._generate_examples_readme())
        generated_files.append(str(examples_readme))

        return generated_files

    def generate_hello_world(self) -> str:
        """Generate Hello World example"""
        comment = self.spec.comment_syntax.get("single_line", "//")

        return f'''{comment} Hello World in {self.spec.name}
{comment} Auto-generated by Illiterate Wizard

print("Hello, World!")
'''

    def generate_fibonacci(self) -> str:
        """Generate Fibonacci sequence example"""
        comment = self.spec.comment_syntax.get("single_line", "//")

        # Try to use language-specific syntax if available
        # Otherwise use a generic template

        return f'''{comment} Fibonacci Sequence in {self.spec.name}
{comment} Auto-generated by Illiterate Wizard
{comment}
{comment} This program calculates and prints the first N Fibonacci numbers

{comment} Recursive Fibonacci function
function fibonacci(n) {{
    if n <= 0 {{
        return 0
    }}
    if n == 1 {{
        return 1
    }}
    return fibonacci(n - 1) + fibonacci(n - 2)
}}

{comment} Iterative version (more efficient)
function fibonacci_iterative(n) {{
    if n <= 0 {{
        return 0
    }}
    if n == 1 {{
        return 1
    }}

    a = 0
    b = 1
    i = 2

    while i <= n {{
        temp = a + b
        a = b
        b = temp
        i = i + 1
    }}

    return b
}}

{comment} Print first 10 Fibonacci numbers
print("First 10 Fibonacci numbers:")
for i = 0; i < 10; i = i + 1 {{
    print(fibonacci(i))
}}

{comment} Print 20th Fibonacci number using iterative method
print("")
print("The 20th Fibonacci number is:")
print(fibonacci_iterative(20))
'''

    def _generate_examples_readme(self) -> str:
        """Generate README for examples directory"""
        return f'''# {self.spec.name} Example Programs

This directory contains example programs written in {self.spec.name}.

## Running Examples

To run any example:

```bash
python ../{self.spec.name.lower()}.py example_name{self.spec.file_extension}
```

## Available Examples

### hello_world{self.spec.file_extension}
The classic "Hello, World!" program. A simple introduction to {self.spec.name}.

**Output:**
```
Hello, World!
```

### fibonacci{self.spec.file_extension}
Calculates Fibonacci numbers using both recursive and iterative approaches.
Demonstrates functions, loops, conditionals, and arithmetic operations.

**Output:**
```
First 10 Fibonacci numbers:
0
1
1
2
3
5
8
13
21
34

The 20th Fibonacci number is:
6765
```

## Learn More

- Check out the [Tutorial](../TUTORIAL.md) for a step-by-step guide
- Read the [Language Reference](../LANGUAGE_REFERENCE.md) for complete documentation

---

*Examples auto-generated by Illiterate Wizard*
'''

    def generate_custom_example(self, name: str, description: str, code: str) -> str:
        """Generate a custom example file"""
        comment = self.spec.comment_syntax.get("single_line", "//")

        return f'''{comment} {name} in {self.spec.name}
{comment} {description}
{comment} Auto-generated by Illiterate Wizard

{code}
'''
